import PDFDocument from 'pdfkit';
import { formatCurrency, sanitizeNumber, sanitizeText } from '../utils/formatCurrency.js';

export function buildCorporateTaxPdfPayload(body = {}) {
  const summary = body.summary || {};
  return {
    companyName: sanitizeText(body.companyName || body.businessName, 'N/A'),
    trn: sanitizeText(body.trn || body.taxRegistrationNumber, 'N/A'),
    businessActivity: sanitizeText(body.businessActivity || body.activity, 'N/A'),
    taxPeriod: sanitizeText(body.taxPeriod, 'N/A'),
    preparedBy: sanitizeText(body.preparedBy, 'UAE VAT & Corporate Tax System'),
    preparedDate: sanitizeText(body.preparedDate, new Date().toISOString().slice(0, 10)),
    summary: {
      revenue: sanitizeNumber(summary.revenue),
      expenses: sanitizeNumber(summary.expenses),
      taxableProfit: sanitizeNumber(summary.taxableProfit),
      taxAmount: sanitizeNumber(summary.taxAmount),
    },
  };
}

export function generateCorporateTaxPdf(payload, out) {
  const doc = new PDFDocument({ size: 'A4', margin: 48 });
  doc.pipe(out);

  doc.fontSize(20).fillColor('#0f172a').text('UAE Corporate Tax Summary', 48, 54);
  doc.fontSize(10).fillColor('#475569').text('Generated by UAE VAT & Corporate Tax System', 48, 80);

  let y = 110;
  const row = (label, value) => {
    doc.fontSize(10).fillColor('#475569').text(label, 48, y, { width: 165 });
    doc.fontSize(10).fillColor('#111827').text(value, 220, y, { width: 320 });
    y += 18;
  };

  row('Company Name', payload.companyName);
  row('Tax Registration Number', payload.trn);
  row('Business Activity', payload.businessActivity);
  row('Tax Period', payload.taxPeriod);
  row('Prepared By', payload.preparedBy);
  row('Prepared Date', payload.preparedDate);

  y += 18;
  doc.fontSize(12).fillColor('#0f172a').text('Computation Summary', 48, y);
  y += 24;

  const amountRow = (label, value) => {
    doc.rect(48, y - 6, 500, 24).stroke('#e2e8f0');
    doc.fontSize(10).fillColor('#111827').text(label, 58, y);
    doc.fontSize(10).fillColor('#111827').text(formatCurrency(value), 390, y, { width: 145, align: 'right' });
    y += 24;
  };

  amountRow('Revenue', payload.summary.revenue);
  amountRow('Expenses', payload.summary.expenses);
  amountRow('Taxable Profit', payload.summary.taxableProfit);
  amountRow('Estimated Corporate Tax', payload.summary.taxAmount);

  y += 20;
  doc.fontSize(9).fillColor('#6b7280').text(
    'Disclaimer: This summary is a calculation aid. Verify records and UAE FTA requirements before final filing.',
    48,
    y,
    { width: 500 }
  );

  doc.end();
}
