import React from 'react';
import { FtaLogo, InfoLine } from '../reportShared';

export function VatReportHeader({ period, generatedDate, vatModeLabel, businessName, trn, emirate, filingFrequency }: any) {
  return <header className='tax-report-header vat-report-header'>
    <div className='vat-report-header-top'>
      <div className='tax-report-brand'>
        <FtaLogo />
        <div><h1>UAE VAT201 Return Summary</h1><p>Generated by UAE VAT &amp; Tax Filing Assistant</p></div>
      </div>
    </div>
    <div className='tax-report-meta compact vat-report-meta-icons'>
      <InfoLine label='📅 Prepared Date' value={generatedDate} />
      <InfoLine label='🗓️ VAT Period' value={period} />
      <InfoLine label='📍 Business Location' value={emirate} />
      <InfoLine label='⚙️ Pricing Mode' value={vatModeLabel} />
    </div>
    <div className='vat-report-summary-row'>
      <div className='vat-report-business-panel'>
        <h3>Business &amp; Filing Information</h3>
        <div className='vat-report-business-grid'>
          <InfoLine label='Business Name' value={businessName || '—'} />
          <InfoLine label='TRN' value={trn || '—'} />
          <InfoLine label='Business Location Emirate' value={emirate} />
          <InfoLine label='VAT Period' value={period} />
          <InfoLine label='Prepared By' value='UAE VAT & Tax Filing Assistant' />
          <InfoLine label='Prepared Date' value={generatedDate} />
          <InfoLine label='VAT Pricing Mode' value={vatModeLabel} />
          <InfoLine label='Filing Frequency' value={filingFrequency || '—'} />
        </div>
      </div>
    </div>
    <div className='tax-report-meta compact vat-report-meta-mobile'>
      <InfoLine label='Business Name' value={businessName || '—'} />
      <InfoLine label='TRN' value={trn || '—'} />
    </div>
  </header>;
}
