import { jsPDF } from 'jspdf';
import { getStoredToken } from '../../../shared/utils/apiClient';

function safeNumber(value: any) {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : 0;
}

function formatMoney(value: any) {
  return new Intl.NumberFormat('en-AE', { style: 'currency', currency: 'AED' }).format(safeNumber(value));
}

function safeText(value: any, fallback = 'N/A') {
  const text = String(value ?? '').trim();
  return text || fallback;
}

function withAuthHeaders(headers: Record<string, string> = {}) {
  const token = getStoredToken();
  return token ? { ...headers, Authorization: `Bearer ${token}` } : headers;
}

function mapCorporatePdfPayload(recordOrPayload: any) {
  const payload = recordOrPayload?.payload || {};
  const periodStart = recordOrPayload?.periodStart || recordOrPayload?.period_start || payload?.financialYearStart || payload?.filing_period_start;
  const periodEnd = recordOrPayload?.periodEnd || recordOrPayload?.period_end || payload?.financialYearEnd || payload?.filing_period_end;

  return {
    companyName: safeText(payload?.companyName || payload?.businessName || recordOrPayload?.companyName || 'Corporate Tax Record'),
    trn: safeText(payload?.taxRegistrationNumber || payload?.trn || recordOrPayload?.trn || 'N/A'),
    businessActivity: safeText(payload?.businessActivity || payload?.activity || recordOrPayload?.businessActivity || 'N/A'),
    taxPeriod:
      safeText(recordOrPayload?.taxPeriod || (periodStart && periodEnd ? `${String(periodStart).slice(0, 10)} to ${String(periodEnd).slice(0, 10)}` : 'Saved Period')),
    preparedBy: 'UAE VAT & Corporate Tax System',
    preparedDate: new Date().toISOString().slice(0, 10),
    summary: {
      revenue: safeNumber(recordOrPayload?.revenue ?? recordOrPayload?.sales_total ?? payload?.revenue ?? payload?.totalRevenue),
      expenses: safeNumber(recordOrPayload?.expenses ?? recordOrPayload?.expenses_total ?? payload?.directExpenses ?? payload?.totalExpenses),
      taxableProfit: safeNumber(recordOrPayload?.taxableProfit ?? recordOrPayload?.taxable_profit ?? recordOrPayload?.taxable_amount ?? payload?.taxableIncome),
      taxAmount: safeNumber(recordOrPayload?.taxAmount ?? recordOrPayload?.tax_amount ?? recordOrPayload?.corporate_tax_estimate ?? payload?.taxPayable),
    },
  };
}

async function requestCorporateTaxPdfBlob(recordOrPayload: any): Promise<Blob> {
  const pdfPayload = mapCorporatePdfPayload(recordOrPayload);
  const response = await fetch('/api/corporate-tax/pdf', {
    method: 'POST',
    credentials: 'include',
    headers: withAuthHeaders({ 'Content-Type': 'application/json' }),
    body: JSON.stringify(pdfPayload),
  });

  if (!response.ok) {
    let message = 'Failed to generate Corporate Tax PDF';
    const contentType = response.headers.get('content-type') || '';
    if (contentType.includes('application/json')) {
      const data = await response.json().catch(() => null);
      message = data?.message || data?.error || message;
    }
    throw new Error(message);
  }

  return response.blob();
}

function downloadBlob(blob: Blob, filename: string) {
  const url = window.URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => window.URL.revokeObjectURL(url), 0);
}

async function fallbackClientPdf(recordOrPayload: any, filename: string) {
  const payload = mapCorporatePdfPayload(recordOrPayload);
  const doc = new jsPDF('p', 'mm', 'a4');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('UAE Corporate Tax Summary', 14, 18);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('Generated by UAE VAT & Corporate Tax System', 14, 24);

  let y = 34;
  const line = (label: string, value: string) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, 14, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 62, y);
    y += 7;
  };

  line('Company Name', safeText(payload.companyName));
  line('Tax Registration', safeText(payload.trn));
  line('Business Activity', safeText(payload.businessActivity));
  line('Tax Period', safeText(payload.taxPeriod));
  y += 2;
  line('Revenue', formatMoney(payload.summary.revenue));
  line('Expenses', formatMoney(payload.summary.expenses));
  line('Taxable Profit', formatMoney(payload.summary.taxableProfit));
  line('Estimated Corporate Tax', formatMoney(payload.summary.taxAmount));

  y += 4;
  doc.setFontSize(9);
  doc.text('Disclaimer: Verify records and UAE FTA requirements before final filing.', 14, y);
  doc.save(filename);
}

export async function downloadCorporateTaxPdf(recordOrPayload: any, preferredFileName?: string) {
  const payload = mapCorporatePdfPayload(recordOrPayload);
  const safeName = payload.companyName.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-_]/g, '') || 'corporate-tax';
  const safePeriod = payload.taxPeriod.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-_]/g, '') || 'period';
  const filename = preferredFileName || `${safeName}-${safePeriod}-corporate-tax.pdf`;

  try {
    const blob = await requestCorporateTaxPdfBlob(recordOrPayload);
    downloadBlob(blob, filename);
    return;
  } catch (error) {
    console.warn('Corporate Tax server PDF failed, falling back to client-side PDF.', error);
  }

  await fallbackClientPdf(recordOrPayload, filename);
}

export async function downloadCorporateTaxHistoryPdf(record: any) {
  return downloadCorporateTaxPdf(record, undefined);
}
