import { jsPDF } from 'jspdf';

function safeNumber(value: any) {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : 0;
}

function formatMoney(value: any) {
  return new Intl.NumberFormat('en-AE', { style: 'currency', currency: 'AED' }).format(safeNumber(value));
}

function safeText(value: any, fallback = 'N/A') {
  const text = String(value ?? '').trim();
  return text || fallback;
}

export async function downloadCorporateTaxHistoryPdf(record: any) {
  const payload = record?.payload || {};
  const periodStart = record?.periodStart || record?.period_start || payload?.financialYearStart || payload?.filing_period_start;
  const periodEnd = record?.periodEnd || record?.period_end || payload?.financialYearEnd || payload?.filing_period_end;

  const companyName = safeText(payload?.companyName || payload?.businessName || 'Corporate Tax Record');
  const trn = safeText(payload?.taxRegistrationNumber || payload?.trn || 'N/A');
  const activity = safeText(payload?.businessActivity || payload?.activity || 'N/A');
  const periodLabel = periodStart && periodEnd ? `${String(periodStart).slice(0, 10)} to ${String(periodEnd).slice(0, 10)}` : 'Saved Period';

  const revenue = safeNumber(record?.revenue ?? record?.sales_total ?? record?.taxable_sales ?? payload?.revenue ?? payload?.totalRevenue);
  const expenses = safeNumber(record?.expenses ?? record?.expenses_total ?? payload?.directExpenses ?? payload?.totalExpenses);
  const taxableProfit = safeNumber(record?.taxableProfit ?? record?.taxable_profit ?? record?.taxable_amount ?? payload?.taxableIncome);
  const taxAmount = safeNumber(record?.taxAmount ?? record?.tax_amount ?? record?.corporate_tax_estimate ?? payload?.taxPayable);

  const doc = new jsPDF('p', 'mm', 'a4');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('UAE Corporate Tax Summary', 14, 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('Generated by UAE VAT & Corporate Tax System', 14, 24);

  let y = 34;
  const line = (label: string, value: string) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, 14, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 62, y);
    y += 7;
  };

  line('Company Name', companyName);
  line('Tax Registration', trn);
  line('Business Activity', activity);
  line('Tax Period', periodLabel);
  y += 2;

  doc.setFont('helvetica', 'bold');
  doc.text('Computation Summary', 14, y);
  y += 7;
  line('Revenue', formatMoney(revenue));
  line('Expenses', formatMoney(expenses));
  line('Taxable Profit', formatMoney(taxableProfit));
  line('Estimated Corporate Tax', formatMoney(taxAmount));

  y += 4;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Disclaimer: Verify records and UAE FTA requirements before final filing.', 14, y);

  const safeName = companyName.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-_]/g, '');
  const safePeriod = periodLabel.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-_]/g, '');
  doc.save(`${safeName}-${safePeriod}-corporate-tax-history.pdf`);
}
